# Generated by Django 5.1.6 on 2025-02-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firmware'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='gateway',
            field=models.CharField(default='0.0.0.0', max_length=15, verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(choices=[('Hikvision', 'Hikvision'), ('Dahua', 'Dahua'), ('Intelbras', 'Intelbras'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='porta_http',
            field=models.IntegerField(default=80, verbose_name='Porta HTTP'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='porta_rtsp',
            field=models.IntegerField(default=554, verbose_name='Porta RTSP'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='porta_servico',
            field=models.IntegerField(default=8000, verbose_name='Porta Serviço'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='senha',
            field=models.CharField(default='1234', max_length=50, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='submask',
            field=models.CharField(default='255.255.255.0', max_length=15, verbose_name='Submask'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='usuario',
            field=models.CharField(default='admin', max_length=50, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('Câmera', 'Câmera'), ('DVR', 'DVR'), ('NVR', 'NVR'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Tipo'),
        ),
    ]
